# Generated by Django 2.0 on 2017-12-31 10:33

import Schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_email', models.CharField(blank=True, max_length=100, null=True)),
                ('about_applicant', models.CharField(blank=True, max_length=200, null=True)),
                ('why_to_join', models.CharField(blank=True, max_length=200, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=Schools.models.resume_upload_dir)),
            ],
            options={
                'verbose_name': 'resumes',
            },
        ),
    ]
